Controllers/VisiterController.cs
using Car.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Car.Controllers
{
    public class VisiterController : Controller
    {
        // GET: Visiter
        dbCAR2DataContext db = new dbCAR2DataContext();
        private int TongView()
        {
            int iTongView = 0;
            iTongView = db.VIEWs.Sum(n=>n.View1);
            
            return iTongView;
        }
        
        public ActionResult ViewCount()
        {         
            ViewBag.TongView = TongView();
            return PartialView(db.VIEWs.SingleOrDefault(n => n.Ngay == DateTime.Now));
        }
        private int TongViewAdmin()
        {
            int iTongViewAd = 0;
            iTongViewAd = db.ADMINs.Sum(n=>n.MaAD);
            return iTongViewAd;
        }
        public ActionResult AdminCount()
        {
            ViewBag.Admin = db.ADMINs.Count();
       
            ViewBag.User = db.KhachHangs.Count(); 
            return PartialView();
        }
        public ActionResult MyChart()
        {
            ;
            decimal Jan = db.DonHangs.Count(n => n.NgayDat.Month == 1);
            decimal Feb = db.DonHangs.Count(n => n.NgayDat.Month == 2);
            decimal Mar = db.DonHangs.Count(n => n.NgayDat.Month == 3);
            decimal Apr = db.DonHangs.Count(n => n.NgayDat.Month == 4);
            decimal May = db.DonHangs.Count(n => n.NgayDat.Month == 5);
            decimal Jun = db.DonHangs.Count(n => n.NgayDat.Month == 6);
            decimal Jul = db.DonHangs.Count(n => n.NgayDat.Month == 7);
            decimal Aug = db.DonHangs.Count(n => n.NgayDat.Month == 8);
            decimal Sept = db.DonHangs.Count(n => n.NgayDat.Month == 9);
            decimal Oct = db.DonHangs.Count(n => n.NgayDat.Month == 10);
            decimal Nov = db.DonHangs.Count(n => n.NgayDat.Month == 11);
            decimal Dec = db.DonHangs.Count(n => n.NgayDat.Month == 12);
            new Chart(width: 750, height: 200)
                .AddSeries(
                    chartType: "column",
                    xValue : new[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec", },
                    yValues : new[] { Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sept, Oct, Nov, Dec }
                ).Write("png");

            return null;
        }
    }
}

Views/Admin/DSAdmin.cshtml
@model PagedList.PagedList<Car.Models.ADMIN>
@using Car.Models
@using PagedList.Mvc;

@helper Truncate(string input, int length)
{
    if (input.Length < length)
    {
        @input
    }
    else
    {
        @input.Substring(0, length)<text>....</text>
    }
}
@{
    ViewBag.Title = "Danh sách admin";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-header">
    <h3 class="float-left"><i class="fas fa-user-tie"></i> Danh Sách Admin</h3>
    <div class="col-md-6 float-right">
        <a href="@Url.Action("Themadmin", "Admin")" class="btn btn-red float-right"><i class="fas fa-plus"></i> Thêm mới</a>
        <div class="col-md-7 float-right">
            @using (Html.BeginForm("DSAdmin", "Admin", FormMethod.Post))
            {
                <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                    <div class="input-group">
                        <input type="text" class="form-control" name="search" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-blue" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            }
        </div>
    </div>
</div>
<div class="card-body">
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" cellspacing="0">
            <thead>
                <tr>
                    <th><i class="fas fa-user-alt"></i> Họ và Tên</th>
                    <th><i class="fas fa-user"></i> Tài khoản đăng nhập</th>
                    <th><i class="far fa-envelope"></i> Email</th>
                    <th><i class="fas fa-phone"></i> Điện thoại</th>
                    <th><i class="fas fa-eye"></i> Quyền</th>
                    <th width="110px"><i class="fas fa-cogs"></i> Chức năng</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.HoTen)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Taikhoan)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DienThoai)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Role)
                    </td>
                    <td class="function">
                        <a href="@Url.Action("Suaadmin","Admin", new { id = item.MaAD })" class="btn btn-blue"><i class="far fa-edit"></i></a>
                        <a href="@Url.Action("Xoaadmin","Admin", new { id = item.MaAD })" class="btn btn-red"><i class="far fa-trash-alt"></i></a>
                    </td>
                </tr>
                }

            </tbody>
        </table>
      
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount

        @Html.PagedListPager(Model, page => Url.Action("DSAdmin", new { page = page }))

    </div>
</div>
<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>

Views/Admin/Index.cshtml

@{
    ViewBag.Title = "Thống kê";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-header">
    <i class="fas fa-chart-area"></i>
    Area Chart Visiter
</div>
<div class="card-body">

    <img src="@Url.Action("MyChart","Visiter")" width="100%" />
</div>
<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>

</div>
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        View Data Table
    </div>
    <div class="card-body">
        <div class="table-responsive">
            @Html.Action("ViewCount", "Visiter")
            @Html.Action("AdminCount", "Visiter")
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th><i class="fas fa-exchange-alt"></i> Đơn hàng bán được</th>

                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>3</td>

                    </tr>

                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>

Views/Admin/NhaCungCap.cshtml
@model PagedList.PagedList<Car.Models.NhaCungCap>
@using Car.Models
@using PagedList.Mvc;

@{
    ViewBag.Title = "Nhà cung cấp";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-header">
    <h3 class="float-left"><i class="fas fa-building"></i>  Danh Sách Nhà Cung cấp</h3>
    <div class="col-md-6 float-right">
        <a href="@Url.Action("ThemNhaCC", "Admin")" class="btn btn-red float-right"><i class="fas fa-plus"></i> Thêm mới</a>
        <div class="col-md-7 float-right">
            @using (Html.BeginForm("NhaCungCap", "Admin", FormMethod.Post))
            {
                <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                    <div class="input-group">
                        <input type="text" class="form-control" name="search" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-blue" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            }
        </div>
    </div>
</div>
<div class="card-body">
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" cellspacing="0">
            <thead>
                <tr>
                    <th><i class="fas fa-building"></i> Tên Nhà cung cấp</th>
                    <th><i class="fas fa-user-alt"></i> Tên Đại diện</th>
                    <th><i class="fas fa-map-marker-alt"></i> Địa chỉ</th>
                    <th><i class="fas fa-phone"></i> Điện thoại</th>
                    <th width="110px"><i class="fas fa-cogs"></i> Chức năng</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenNCC)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenDaiDien)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DiaChi)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SoDTT)
                        </td>
                        <td class="function">
                            <a href="@Url.Action("SuaNhaCC","Admin", new { id = item.ID })" class="btn btn-blue"><i class="far fa-edit"></i></a>
                            <a href="@Url.Action("XoaNCC","Admin", new { id = item.ID })" class="btn btn-red"><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                }

            </tbody>
        </table>

        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount

        @Html.PagedListPager(Model, page => Url.Action("NhaCungCap", new { page = page }))

    </div>
</div>


Views/Admin/QLUser.cshtml
@model PagedList.PagedList<Car.Models.KhachHang>
@using Car.Models
@using PagedList.Mvc;

@{
    ViewBag.Title = "Quản lý User";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-header">
    <h3 class="float-left"><i class="fas fa-users"></i> Quản Lý User</h3>
    <div class="col-md-6 float-right">
        <a href="@Url.Action("ThemUser", "Admin")" class="btn btn-red float-right"><i class="fas fa-plus"></i> Thêm mới</a>
        <div class="col-md-7 float-right">
            @using (Html.BeginForm("QLUser", "Admin", FormMethod.Post))
            {
                <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                    <div class="input-group">
                        <input type="text" class="form-control" name="search" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-blue" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            }
        </div>
    </div>
</div>
<div class="card-body">
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" cellspacing="0">
            <thead>
                <tr>
                    <th><i class="fas fa-user"></i> Tài khoản đăng nhập</th>
                    <th><i class="fas fa-unlock"></i> Pass</th>
                    <th><i class="fas fa-user-alt"></i> Họ và Tên</th>
                    <th><i class="far fa-envelope"></i> Email</th>
                    <th><i class="fas fa-phone"></i> Điện thoại</th>
                    <th width="110px"><i class="fas fa-cogs"></i> Chức năng</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Taikhoan)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pass)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HoTen)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DienThoai)
                    </td>
                    <td class="function">
                        <a href="@Url.Action("SuaUser","Admin", new { id = item.MaKH })" class="btn btn-blue"><i class="far fa-edit"></i></a>
                        <a href="@Url.Action("XoaUser","Admin", new { id = item.MaKH })" class="btn btn-red"><i class="far fa-trash-alt"></i></a>
                    </td>
                </tr>
                }

            </tbody>
        </table>
        @*<div class="float-right">
                <ul class="pagination">
                    @while (Model.PageCount > Model.PageNumber)
                    {
                        <li class="page-item disabled">
                            <span class="page-link">Previous</span>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="@Url.Action("QLLoai","Admin",new { page = Model.PageNumber})">@Model.PageNumber</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">Next</a>
                        </li>
                    }

                </ul>
            </div>*@
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount

        @Html.PagedListPager(Model, page => Url.Action("QLUser", new { page = page }))

    </div>
</div>
<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>

Views/Admin/Sanpham.cshtml
@model PagedList.PagedList<Car.Models.SanPham>
@using Car.Models
@using PagedList.Mvc;

@helper Truncate(string input, int length)
{
    if (input.Length < length)
    {
        @input
    }
    else
    {
        @input.Substring(0, length)<text>....</text>
    }
}
@{
    ViewBag.Title = "Sản phẩm phụ kiện phụ tùng";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-header">
    <h3 class="float-left"><i class="fas fa-cube"></i> Quản Lý Thông Tin Sản Phẩm</h3>
    <div class="col-md-6 float-right">
        <a href="@Url.Action("Themmoisp", "Admin")" class="btn btn-red float-right"><i class="fas fa-plus"></i> Thêm mới</a>
        <div class="col-md-7 float-right">
            @using (Html.BeginForm("Sanpham", "Admin", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                    <div class="input-group">
                        <input type="text" class="form-control" name="search" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-blue" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            }
        </div>
    </div>
</div>
<div class="card-body">
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" cellspacing="0">
            <thead>
                <tr>
                    <th width="10%"><i class="fas fa-barcode"></i> Mã NSX</th>
                    <th><i class="fas fa-cube"></i> Tên sản phẩm : </th>
                    <th><i class="fas fa-sort-amount-up"></i> Số lượng</th>
                    <th><i class="fas fa-comment-alt"></i> Mô tả</th>
                    <th><i class="fas fa-dollar-sign"></i> Giá bán (VND)</th>
                    <th><i class="fas fa-image"></i> Ảnh Bìa</th>
                    <th><i class="fas fa-cubes"></i> Loại</th>
                    <th width="9%"><i class="fas fa-cogs"></i> Chức năng</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.MaSP)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenSP)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SoLuong)
                        </td>
                        <td>
                            @Truncate(item.MoTa, 100)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.GiaBan)
                        </td>
                        <td>
                            <img src="@Url.Content("~/Hinhsanpham/" + item.AnhBia)" style="height:100px ; width:130px" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LoaiSP.TenLoai)
                        </td>
                        <td class="function">
                            <a href="@Url.Action("Suasp","Admin", new { id = item.MaSP })" class="btn btn-blue"><i class="far fa-edit"></i></a>
                            <a href="@Url.Action("Xoasp","Admin", new { id = item.MaSP })" class="btn btn-red"><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
        @*<div class="float-right">
                <ul class="pagination">
                    @while (Model.PageCount > Model.PageNumber)
                    {
                        <li class="page-item disabled">
                            <span class="page-link">Previous</span>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="@Url.Action("QLLoai","Admin",new { page = Model.PageNumber})">@Model.PageNumber</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">Next</a>
                        </li>
                    }

                </ul>
            </div>*@
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount

        @Html.PagedListPager(Model, page => Url.Action("SanPham", new { page = page }))

    </div>
</div>
<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>

Views/Admin/SuaNsx.cshtml
@model Car.Models.NhaSanXuat

@{
    ViewBag.Title = "Sửa nhà sản xuất";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-header">
    <h3 class="float-left" style="color:blue"><i class="fas fa-edit"></i> Sửa Nhà sản xuất</h3>
</div>
<div class="card-body">
    <div class="table-responsive">

        @using (Html.BeginForm("SuaNsx", "Admin", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.MaNSX)
            <div class="col-md-12">
                <div class="form-group" style="padding-bottom:30px">
                    <div class="col-md-4 float-left">
                        <i class="fas fa-cube"></i>
                        @Html.LabelFor(model => model.TenNSX, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-8 float-right">
                        @Html.EditorFor(model => model.TenNSX, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenNSX, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">

                <div class=" col-md-12 float-left">
                    <button type="submit" class="btn btn-red float-right"><i class="fas fa-edit"></i> Sửa</button>
                    <a href="@Url.Action("QLNsx","Admin")" class="btn btn-secondary"><i class="fas fa-arrow-left"></i> Trở lại</a>
                </div>
            </div>
        }
    </div>
</div>

Views/Admin/SuaQC.cshtml
@model Car.Models.QuangCao
@{
    ViewBag.Title = "Sửa quảng cáo";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-header">
    <h3 class="float-left" style="color:blue"><i class="fas fa-edit"></i> Sửa Quảng cáo</h3>
</div>
<div class="card-body">
    <div class="table-responsive">

        @using (Html.BeginForm("SuaQC", "Admin", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-4 float-left">
                        <i class="fas fa-user"></i>
                        @Html.LabelFor(model => model.TenQC, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-8 float-right">
                        @Html.EditorFor(model => model.TenQC, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                        @Html.ValidationMessageFor(model => model.TenQC, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 float-left">
                        <i class="fas fa-building"></i>
                        @Html.LabelFor(model => model.IDNCC, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-8 float-right">
                        @Html.DropDownList("IDNCC", null, new { @class = "btn btn-default dropdown-toggle" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4 float-left">
                        <i class="fas fa-image"></i>
                        @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-8 float-right">
                        <input type="file" name="fileupload" class="form-control" />
                        @ViewBag.Thongbao
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 float-left">
                        <i class="fas fa-sitemap"></i>
                        @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-8 float-right">
                        @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control", @type = "email" } })
                        @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class=" col-md-12 float-left">
                    <button type="submit" class="btn btn-blue float-right"><i class="fas fa-edit"></i> Sửa</button>
                    <a href="@Url.Action("QuangCao","Admin")" class="btn btn-secondary"><i class="fas fa-arrow-left"></i> Trở lại</a>
                </div>
            </div>
        }
    </div>
</div>

Views/Admin/Sualoai.cshtml
@model Car.Models.LoaiSP

@{
    ViewBag.Title = "Sửa loại";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="card-header">
    <h3 class="float-left" style="color:red"><i class="fas fa-edit"></i> Sửa loại</h3>
</div>
<div class="card-body">
    <div class="table-responsive">
        @using (Html.BeginForm("Sualoai", "Admin", FormMethod.Post, new { @class = "form-horizontal", @enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.MaLoai)
            <div class="form-group">
                <label for="IdBrand" class="control-label col-md-2">Mã loại</label>
                <div class="col-md-10">
                    <input type="text" name="IdBrand" id="IdBrand" class="form-control text-box" value="@Model.MaLoai" readonly />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-2">
                    <i class="fas fa-cube"></i>
                    @Html.LabelFor(model => model.TenLoai, htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-10">
                    <input type="text" name="TenLoai" id="TenLoai" class="form-control text-box" placeholder="Nhập tên loại ..." value="@Model.TenLoai" />
                    @Html.ValidationMessageFor(model => model.TenLoai, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class=" col-md-12 ">
                    <button type="submit" class="btn btn-blue float-right"><i class="fas fa-edit"></i> Sửa</button>
                    <a href="@Url.Action("QLLoai","Admin")" class="btn btn-secondary"><i class="fas fa-arrow-left"></i> Trở lại</a>
                </div>
            </div>

        }

    </div>
</div>


Views/Admin/TaiKhoan.cshtml
@if (Model != null)
{


    <span style="color:red">Xin Chào <a href=@Url.Action("SuaTT","Admin") style="color:red">@Model.HoTen</a></span>
    <a class="btn-primary btn-sm" href=@Url.Action("Dangxuat","Admin")>Đăng Xuất</a>
}


Views/Admin/ThemNsx.cshtml
@model Car.Models.NhaSanXuat

@{
    ViewBag.Title = "Thêm nhà sản xuất";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-header">
    <h3 class="float-left" style="color:red"><i class="fas fa-plus"></i> Thêm Mới Nhà sản xuất</h3>
</div>
<div class="card-body">
    <div class="table-responsive">

        @using (Html.BeginForm("ThemNsx", "Admin", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="col-md-12">
                <div class="form-group" style="padding-bottom:30px">
                    <div class="col-md-4 float-left">
                        <i class="fas fa-cube"></i>
                        @Html.LabelFor(model => model.TenNSX, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-8 float-right">
                        @Html.EditorFor(model => model.TenNSX, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenNSX, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">

                <div class=" col-md-12 float-left">
                    <button type="submit" class="btn btn-red float-right"><i class="fas fa-plus"></i> Thêm mới</button>
                    <a href="@Url.Action("QLNsx","Admin")" class="btn btn-secondary"><i class="fas fa-arrow-left"></i> Trở lại</a>
                </div>
            </div>
        }
    </div>
</div>

Views/Admin/Themloai.cshtml
@model Car.Models.LoaiSP

@{
    ViewBag.Title = "Thêm loại";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-header">
    <h3 class="float-left" style="color:red"><i class="fas fa-plus"></i> Thêm loại</h3>   
</div>
<div class="card-body">
    <div class="table-responsive">
        @using (Html.BeginForm("Themloai", "Admin", FormMethod.Post, new { @class = "form-horizontal", @enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <div class="col-md-2">
                    <i class="fas fa-cube"></i>
                    @Html.LabelFor(model => model.TenLoai, htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-10 float-right">

                    <input type="text" name="TenLoai" id="TenLoai" class="form-control text-box" placeholder="Nhập tên loại ..." />
                    @Html.ValidationMessageFor(model => model.TenLoai, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class=" col-md-12 ">
                    <button type="submit" class="btn btn-red float-right"><i class="fas fa-plus"></i> Thêm mới</button>
                    <a href="@Url.Action("QLLoai","Admin")" class="btn btn-secondary"><i class="fas fa-arrow-left"></i> Trở lại</a>
                </div>
            </div>

        }

    </div>
</div>