Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Car.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index(string name, string email, string message)
        {
            try
            {
                //Configuring webMail class to send emails  
                //gmail smtp server  
                WebMail.SmtpServer = "smtp.gmail.com";
                //gmail port to send emails  
                WebMail.SmtpPort = 587;
                WebMail.SmtpUseDefaultCredentials = true;
                //sending emails with secure protocol  
                WebMail.EnableSsl = true;
                //EmailId used to send emails from application  
                WebMail.UserName = "buiquangductri@gmail.com";
                WebMail.Password = "";

                //Sender email address.  
                WebMail.From = "buiquangductri@gmail.com";

                //Send email  
                WebMail.Send(to: email, subject: "góp ý", body: email + "  đã gửi "+ name +" là người  " + " nội dung " + message, cc: null, bcc: null, isBodyHtml: true);
                ViewBag.Status = "Email Sent Successfully.";
            }
            catch (Exception)
            {
                ViewBag.Status = "Problem while sending email, Please check details.";

            }
            return View();
        }
    }
}

Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Car.Models;

using PagedList;
using PagedList.Mvc;

namespace Car.Controllers
{
    public class CarController : Controller
    {
        // GET: Car
       
        dbCAR2DataContext data = new dbCAR2DataContext();
        private List<NhaSanXuat> NSX(int count)
        {
            return data.NhaSanXuats.OrderByDescending(b => b.TenNSX).Take(count).ToList();
        }
        private List<Xe> Layxemoi(int count)
        {
            return data.Xes.OrderByDescending(a => a.NamSanXuat).Take(count).ToList();
        }
        private List<SanPham> Layspmoi(int count)
        {
            return data.SanPhams.OrderByDescending(b => b.TenSP).Where(b => b.Xoa == false).Take(count).ToList();
        }

        public ActionResult Index(int ? page,VIEW v)
        {
            if (Session["VisitorsCount"] != null)
            {
                
                DateTime today = DateTime.Now.Date;
                var v1 = data.VIEWs.Where(a => a.Ngay == today).FirstOrDefault();
                if (v1 == null)
                {
                    v.Ngay = today;
                    v.View1 += 1;
                    data.VIEWs.InsertOnSubmit(v);
                    data.SubmitChanges();
                }
                else
                {
                    VIEW sp = data.VIEWs.SingleOrDefault(n => n.Ngay == today);
                    sp.View1 += 1;
                    UpdateModel(sp);
                    data.SubmitChanges();
                }
            }
            
            var list = data.NhaSanXuats.OrderBy(n=>n.TenNSX).ToList();
            ViewBag.nhasan = list;
            int pageSize = 8;
            int pageNum = (page ?? 1);

            var xemoi = Layxemoi(10);
            return View(xemoi.ToPagedList(pageNum,pageSize));
        }
        
        public ActionResult PhuTung(int ? page, string sortOrder)
        {

            ViewBag.NameParm = String.IsNullOrEmpty(sortOrder) ? "NameParm_desc" : "";
            ViewBag.GiaParm = sortOrder == "GiaParm" ? "GiaParm_desc" : "GiaParm";
            int pageSize = 8;
            int pageNum = (page ?? 1);
            var list = data.LoaiSPs.OrderBy(n => n.TenLoai).ToList();
            ViewBag.loaisp = list;
            var ptmoi = Layspmoi(10);
            var sanpham = ptmoi.ToPagedList(pageNum, pageSize);

            switch (sortOrder)
            {
                case "NameParm_desc":
                    sanpham = ptmoi.OrderByDescending(n => n.TenSP).ToPagedList(pageNum, pageSize);
                    break;
                case "GiaParm":
                    sanpham = ptmoi.OrderBy(n => n.GiaBan).ToPagedList(pageNum, pageSize);
                    break;
                case "GiaParm_desc":
                    sanpham = ptmoi.OrderByDescending(n => n.GiaBan).ToPagedList(pageNum, pageSize);
                    break;
                default:
                    sanpham = ptmoi.OrderBy(n => n.TenSP).ToPagedList(pageNum, pageSize);
                    break;
            }

            return View(sanpham);
        }
        
        public ActionResult PhuTungDetails(int id)
        {
            var sp = from s in data.SanPhams
                     where s.MaSP == id
                     select s;
            var list = data.SanPhams.OrderBy(n => n.TenSP).Where(n=>n.MaSP != id ).ToList();
            ViewBag.splq = list;
            return View(sp.Single());
        }
        public ActionResult CarDetails(int id)
        {
            var xe = from x in data.Xes
                     where x.Maxe == id
                     select x;
            var list = data.Xes.OrderBy(n => n.Tenxe).Where(n=>n.Maxe != id).ToList();
            ViewBag.nhasx = list;
            return View(xe.Single());
        }
        public ActionResult Intro()
        {
            return View();
        }
        public ActionResult Search(string searchTerm)
        {
            var xes = from b in data.Xes select b;

            if (!String.IsNullOrEmpty(searchTerm))
            {
                xes = data.Xes.Where(b => b.Tenxe.Contains(searchTerm));
            }
            ViewBag.SearchTerm = searchTerm;
            return View(xes);
        }
       
    }
}

Controllers/NguoidungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Car.Models;
using System.Threading.Tasks;
using System.Web.Helpers;

namespace Car.Controllers
{

    public class NguoidungController : Controller
    {
        dbCAR2DataContext db = new dbCAR2DataContext();
        // GET: Nguoidung

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Dangky()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangky(FormCollection collection, KhachHang kh)
        {
            
            var hoten = collection["HoTenKH"];
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            var nhaplai = collection["Nhaplaimk"];
            var dienthoai = collection["Dienthoai"];
            var email = collection["Diachimail"];
            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["loi1"] = "Nhập họ tên!";
            }
            else if (String.IsNullOrEmpty(tendn))
            {
                ViewData["loi2"] = "Nhập tên đăng nhập!";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["loi3"] = "Nhập mật khẩu!";
            }
            else if (String.IsNullOrEmpty(nhaplai) && nhaplai != matkhau)
            {
                ViewData["loi4"] = "Phải khớp với mật khẩu!";
            }
            else if (String.IsNullOrEmpty(dienthoai))
            {
                ViewData["loi5"] = "Nhập điên thoại";
            }
            else if (String.IsNullOrEmpty(email))
            {
                ViewData["loi6"] = "Nhập Email!";
            }
            else
            {
                var t = from a in db.KhachHangs where a.Taikhoan == collection["TenDN"].ToString() select a;
                if (t.ToList().Count!=0 )
                {
                    ViewData["loi7"] = "dang ky loi!";
                }
                else
                {
                    try
                    {
                        //Configuring webMail class to send emails  
                        //gmail smtp server  
                        WebMail.SmtpServer = "smtp.gmail.com";
                        //gmail port to send emails  
                        WebMail.SmtpPort = 587;
                        WebMail.SmtpUseDefaultCredentials = true;
                        //sending emails with secure protocol  
                        WebMail.EnableSsl = true;
                        //EmailId used to send emails from application  
                        WebMail.UserName = "buiquangductri@gmail.com"; // email de gui
                        WebMail.Password = "";//nhap mat khau vao day ^^ 

                        //Sender email address.  
                        WebMail.From = "buiquangductri@gmail.com"; // nguoi gui email

                        //Send email  
                        WebMail.Send(to: email, subject: "cảm ơn bạn đã đăng kí tới DCG-Cars", body: "Tai khoan : " + tendn + " Pass : " + matkhau, cc: null, bcc: null, isBodyHtml: true);

                    }
                    catch (Exception)
                    {
                        ViewBag.Status = "Problem while sending email, Please check details.";

                    }
                    
                    kh.HoTen = hoten;
                    kh.Taikhoan = tendn;
                    kh.Pass = matkhau;
                    kh.Email = email;
                    kh.DienThoai = dienthoai;
                    db.KhachHangs.InsertOnSubmit(kh);
                    db.SubmitChanges();
                    return RedirectToAction("Dangnhap");
                }
            }
            
            return this.Dangky();
        }
        public ActionResult TaiKhoan()
        {
            if (Session["TaiKhoan"] == null )
            {
                return PartialView();
            }
            else 
            {
                    var query = db.KhachHangs.SingleOrDefault(k => k.Taikhoan == Session["Taikhoan"].ToString());
                    return PartialView(query);
            }
        }
        public ActionResult Dangnhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangnhap(FormCollection collection)
        {
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            KhachHang tk = db.KhachHangs.SingleOrDefault(n => n.Taikhoan == tendn && n.Pass == matkhau);
             if (tk != null)
            {
                ViewBag.ThongBao = "Chúc mừng bạn đã đăng nhập thành công!";
                Session["TaiKhoan"] = tk.Taikhoan;
                Session["KH"] = tk;
                Session["MaKH"] = tk.MaKH;
                Session["TenKH"] = tk.HoTen;
                Session["EmailKH"] = tk.Email;
                return RedirectToAction("Index", "Car");
            }
            else ViewBag.Thongbao = "Tên đăng nhập hoặc tài khoản không đúng";
            return View();
           
        }
        public ActionResult DangXuat()
        {
            Session["TaiKhoan"] = null;
            Session["Giohang"] = null;
            return RedirectToAction("Index", "Car");
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(FormCollection collection)
        {
            var tendn = collection["username"];
            var matkhau = collection["password"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "phải nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "phải nhập mật khẩu";
            }
            else
            {
                ADMIN ad = db.ADMINs.SingleOrDefault(n => n.Taikhoan == tendn && n.Pass == matkhau);
                if (ad != null)
                {
                    Session["TaikhoanAdmin"] = ad.HoTen;
                    Session["AdminRole"] = ad.Role;
                    return RedirectToAction("Index", "Admin");
                }
                else
                {
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
                }
            }
            return View();
        }
        public ActionResult Logout()
        {
            Session["TaikhoanAdmin"] = null;
            return RedirectToAction("Index", "WatchStore");
        }
        public ActionResult TTNguoiDung(int id)
        {
            if (Session["TaiKhoan"] != null)
            {
                var ttkh = from s in db.KhachHangs
                         where s.MaKH == id
                         select s;
                return View(ttkh.Single());
            }
            return RedirectToAction("Index", "Car");
        }
        [HttpGet]
        public ActionResult SuaTT(int id)
        {
            if (Session["TaiKhoan"] != null)
            {
                KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.MaKH == id);

                if (kh == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                return View(kh);
            }
            return RedirectToAction("index", "Car");
        }
        [HttpPost, ActionName("SuaTT")]
        [ValidateInput(false)]
        public ActionResult xacnhansuaTT(int id)
        {
            KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.MaKH == id);

            UpdateModel(kh);
            db.SubmitChanges();
            return RedirectToAction("TTNguoiDung","NguoiDung",new { id=kh.MaKH});
        }

        [AllowAnonymous]
        public ActionResult QuenMK()
        {
            return View();
        }
        [HttpPost]
        public ActionResult QuenMK(FormCollection f)
        {
            var email = f["Email"];
            
            KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.Email == email);
            if (kh == null)
            {
                ViewData["loi1"] = "khong co email nay";
            }
            else
            {
                try
                {
                    //Configuring webMail class to send emails  
                    //gmail smtp server  
                    WebMail.SmtpServer = "smtp.gmail.com";
                    //gmail port to send emails  
                    WebMail.SmtpPort = 587;
                    WebMail.SmtpUseDefaultCredentials = true;
                    //sending emails with secure protocol  
                    WebMail.EnableSsl = true;
                    //EmailId used to send emails from application  
                    WebMail.UserName = "buiquangductri@gmail.com";
                    WebMail.Password = ""; //nhap mat khau vao day

                    //Sender email address.  
                    WebMail.From = "buiquangductri@gmail.com";

                    //Send email  
                    WebMail.Send(to: email, subject: "góp ý", body: "Tai khoan : " + kh.Taikhoan  + " Pass : " + kh.Pass, cc: null, bcc: null, isBodyHtml: true);

                }
                catch (Exception)
                {
                    ViewBag.Status = "Problem while sending email, Please check details.";

                }
                return RedirectToAction("Xacnhanquenemail");
            }
            return View();
        }
        public ActionResult Xacnhanquenemail()
        {
            return View();
        }

    }
}

Views/Shared/_LayoutAbout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <title>@ViewBag.title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Responsive Minimal Bootstrap Theme">
    <meta name="keywords" content="onepage,responsive,minimal,bootstrap,theme">
    <meta name="author" content="">
    <!-- CSS Files
    ================================================== -->
    ================================================== -->
    <link rel="stylesheet" href="~/Content/bootstrapv3.css" type="text/css">
    <link rel="stylesheet" href="~/Content/jpreloader.css" type="text/css">
    <link rel="stylesheet" href="~/Content/animate.css" type="text/css">
    <link rel="stylesheet" href="~/Content/plugin.css" type="text/css">
    <link rel="stylesheet" href="~/Content/owl.carousel.css" type="text/css">
    <link rel="stylesheet" href="~/Content/owl.theme.css" type="text/css">
    <link rel="stylesheet" href="~/Content/owl.transitions.css" type="text/css">
    <link rel="stylesheet" href="~/Content/magnific-popup.css" type="text/css">
    <link rel="stylesheet" href="~/Content/style.css" type="text/css">
    <link rel="stylesheet" href="~/Content/Site.css" type="text/css">
    <link rel="stylesheet" href="~/demo/demo.css" type="text/css">

    <!-- custom background -->
    <link rel="stylesheet" href="~/Content/bg.css" type="text/css">

    <!-- color scheme -->
    <link rel="stylesheet" href="~/Content/color.css" type="text/css" id="colors">

    <!-- load fonts -->
    <link rel="stylesheet" href="~/fonts/font-awesome/css/font-awesome.css" type="text/css">
    <link rel="stylesheet" href="~/fonts/elegant_font/HTML_CSS/style.css" type="text/css">
    <link rel="stylesheet" href="~/fonts/et-line-font/style.css" type="text/css">

    <link href="~/fonts/font-awesome/css/fontawesome-all.min.css" rel="stylesheet" />
    <!-- revolution slider -->
    <link rel="stylesheet" href="~/rs-plugin/css/settings.css" type="text/css">
    <link rel="stylesheet" href="~/Content/rev-settings.css" type="text/css">
</head>
<body class="page-about">
    <div id="wrapper">
        <!-- header begin -->
        <header>
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <!-- logo begin -->
                        <h1 id="logo">
                            <a href="@Url.Action("Index", "Car")">
                                <img class="logo" src="~/images/logo.jpg" height="75px" alt="">
                            </a>
                        </h1>
                        <!-- logo close -->
                        <!-- small button begin -->
                        <span id="menu-btn"></span>
                        <!-- small button close -->
                        <!-- mainmenu begin -->
                        <nav>
                            <ul id="mainmenu">
                                <li>
                                    @*<a href="">Trang Chủ</a>*@
                                    <a href="@Url.Action("Index", "Car")">Trang chủ</a>
                                </li>

                                <li><a href="@Url.Action("Index", "About")">Giới Thiệu</a></li>
                                <li>
                                    <a href="">Sản phẩm</a>
                                    <ul>
                                        <li>
                                            <a href="@Url.Action("Index", "Car")">Xe</a>
                                        </li>
                                        <li><a href="@Url.Action("PhuTung", "Car")">Phụ Tùng & Phụ Kiện </a></li>

                                    </ul>
                                </li>
                                <li>
                                    @if (Session["TaiKhoan"] == null)
                                    {
                                        <a href="#">Đăng nhập</a>
                                        <ul>
                                            <li><a href=@Url.Action("Dangnhap", "Nguoidung")><i class="fas fa-sign-in-alt"></i>Đăng nhập</a></li>
                                            <li><a href=@Url.Action("Dangky", "Nguoidung")><i class="fas fa-user-plus"></i>Đăng Ký</a></li>
                                        </ul>
                                    }
                                    else
                                    {
                                        <a href="#" style="color:red">Xin chào @Session["TenKH"]</a>
                                        <ul>
                                            <li><a href="@Url.Action("TTNguoiDung","Nguoidung",new { id=Session["MaKH"]})" style="color:red">Thông tin người dùng</a></li>
                                            <li><a href=@Url.Action("Dangxuat","Nguoidung")>Đăng Xuất</li>
                                        </ul>
                                    }
                                </li>
                                <li> @Html.Action("GioHangpartial", "GioHang")</li>

                            </ul>
                        </nav>
                    </div>
                    <!-- mainmenu close -->
                    <div class="row">
                        <div class="col-md-12" style="text-align:center;margin-top:-17px;">
                            @using (Html.BeginForm("Search", "Car", FormMethod.Get, new { @class = "navbar-form navbar-right", role = "search", id = "search-form" }))
                            {
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Tìm kiếm" name="SearchTerm" value="@ViewBag.SearchTerm" id="search-box">
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary" style="padding:6px 5px;"><i class="fas fa-search" style="margin:4px;"></i></button>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- header close -->
        <!-- content begin -->
        @RenderBody()



        <!-- footer begin -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <img src="~/images/logo.jpg" class="logo-small" alt=""><br>
                    </div>
                    <div class="col-md-4">
                        <div class="widget widget_recent_post">
                            <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Ffacebook&tabs=timeline&width=340&height=150&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=true&appId=523301211388900" width="340" height="150" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <h3>Liên Hệ</h3>
                        <div class="widget widget-address">
                            <address>
                                <span>101 RedStreet </span>
                                <span><strong>Phone:</strong>911</span>
                                <span><strong>Fax:</strong>911</span>
                                <span><strong>Email 1:</strong><a href="mailto:buiquangductri@gmail.com">buiquangductri@gmail.com</a></span>
                                <span><strong>Email 2:</strong><a href="mailto:hakai.prince@gmail.com">hakai.prince@gmail.com</a></span>
                                <span><strong>Web:</strong><a href="#">http://car.somee.com</a></span>
                            </address>
                        </div>
                    </div>
                </div>
            </div>
            <div class="subfooter">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            &copy; Copyright 2015 - Archi by Designesia
                        </div>
                        <div class="col-md-6 text-right">
                            <div class="social-icons">
                                <a href="#"><i class="fa fa-facebook fa-lg"></i></a>
                                <a href="#"><i class="fa fa-twitter fa-lg"></i></a>
                                <a href="#"><i class="fa fa-rss fa-lg"></i></a>
                                <a href="#"><i class="fa fa-google-plus fa-lg"></i></a>
                                <a href="#"><i class="fa fa-skype fa-lg"></i></a>
                                <a href="#"><i class="fa fa-dribbble fa-lg"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- footer close -->
    </div>
    <!-- style switcher
    ================================================== -->
    <!-- Javascript Files
    ================================================== -->
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/jpreLoader.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.isotope.min.js"></script>
    <script src="~/Scripts/easing.js"></script>
    <script src="~/Scripts/jquery.flexslider-min.js"></script>
    <script src="~/Scripts/jquery.scrollto.js"></script>
    <script src="~/Scripts/owl.carousel.js"></script>
    <script src="~/Scripts/jquery.countTo.js"></script>
    <script src="~/Scripts/classie.js"></script>
    <script src="~/Scripts/video.resize.js"></script>
    <script src="~/Scripts/validation.js"></script>
    <script src="~/Scripts/wow.min.js"></script>
    <script src="~/Scripts/jquery.magnific-popup.min.js"></script>
    <script src="~/Scripts/enquire.min.js"></script>
    <script src="~/Scripts/designesia.js"></script>
    <script src="demo/demo.js"></script>
    <!-- SLIDER REVOLUTION SCRIPTS  -->
    <script type="text/javascript" src="~/rs-plugin/js/jquery.themepunch.plugins.min.js"></script>
    <script type="text/javascript" src="~/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>


</body>
</html>

Views/Shared/_SidemenuAdminPartial.cshtml
<ul class="sidebar navbar-nav">
    <li class="nav-item active">
        <a class="nav-link" href="@Url.Action("Index", "Admin")">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Thống kê</span>
        </a>
    </li>
    @if (Convert.ToInt32(Session["AdminRole"]) == 2 || Convert.ToInt32(Session["AdminRole"]) == 0)
    {
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-cubes"></i>
                <span>Phụ tùng, phụ kiện</span>
            </a>
            <div class="dropdown-menu bg-dark" aria-labelledby="pagesDropdown">
                <a class="dropdown-item" href="@Url.Action("QLLoai", "Admin")">
                    <i class="fas fa-cube"></i>
                    <span>QL Loại</span>
                </a>
                <a class="dropdown-item" href="@Url.Action("Sanpham", "Admin")">
                    <i class="fas fa-cube"></i>
                    <span>Sản phẩm Info</span>
                </a>
            </div>
        </li>
    }
    @if (Convert.ToInt32(Session["AdminRole"]) == 1 || Convert.ToInt32(Session["AdminRole"]) == 0)
    {
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-car"></i>
                <span>Xe hơi</span>
            </a>
            <div class="dropdown-menu bg-dark" aria-labelledby="pagesDropdown">
                <a class="dropdown-item" href="@Url.Action("Xe", "Admin")">
                    <i class="fas fa-car"></i>
                    <span>Xe Info</span>
                </a>
                <a class="dropdown-item" href="@Url.Action("QLNsx", "Admin")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>QL NSX</span>
                </a>
            </div>
        </li>
    }
    @if (Convert.ToInt32(Session["AdminRole"]) == 0)
    {
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-users"></i>
                <span>Tài khoản</span>
            </a>
            <div class="dropdown-menu bg-dark" aria-labelledby="pagesDropdown">
                <a class="dropdown-item" href="@Url.Action("DSAdmin", "Admin")">
                    <i class="fas fa-user-tie"></i>
                    <span>Admin Info</span>
                </a>
                <a class="dropdown-item" href="@Url.Action("QLUser", "Admin")">
                    <i class="fas fa-users"></i>
                    <span>QL User</span>
                </a>
            </div>
        </li>
    }

    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-exchange-alt"></i>
            <span>Đơn hàng</span>
        </a>
        <div class="dropdown-menu bg-dark" aria-labelledby="pagesDropdown">
            <a class="dropdown-item" href="@Url.Action("DonHang", "Admin")">
                <i class="fas fa-flag"></i>
                <span>Đơn hàng info</span>
            </a>
            <a class="dropdown-item" href="@Url.Action("QLGiaodich", "Admin")">
                <i class="fas fa-exchange-alt"></i>
                <span>QL Giao dịch</span>
            </a>
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-users"></i>
            <span>Quản lý quảng cáo</span>
        </a>
        <div class="dropdown-menu bg-dark" aria-labelledby="pagesDropdown">
            <a class="dropdown-item" href="@Url.Action("NhaCungCap", "Admin")">
                <i class="fas fa-user-tie"></i>
                <span>Nhà cung cấp</span>
            </a>
            <a class="dropdown-item" href="@Url.Action("QuangCao", "Admin")">
                <i class="fas fa-users"></i>
                <span>Quảng cáo</span>
            </a>
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-users"></i>
            <span>QL Banner</span>
        </a>
        <div class="dropdown-menu bg-dark" aria-labelledby="pagesDropdown">
            <a class="dropdown-item" href="@Url.Action("Banner", "Admin")">
                <i class="fas fa-user-tie"></i>
                <span>Banner</span>
            </a>
        </div>
    </li>
</ul>